import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='pattern h-screen flex justify-center'>

        <h1 className='text-invert text-center self-center text-[15rem] font-black text-inverted leading-[100%]'>Oliver Mansfield Digital.</h1>

      </main>
    </div>
  )
}
